logging:
  config: classpath:logback-spring.xml
  level:
    # 这里设置的日志级别优先于logback-spring.xml文件Loggers中的日志级别。
    cn.wlih: trace
server:
  port: 8080
spring:
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://db.wlih.cn:3307/sensor_module?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: SensorModule
    password: SensorModule_mima202001040435
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    #数据库索引
    database: 0
    host: db.wlih.cn
    port: 6379
    password: Admin@10086
    jedis:
      pool:
        #最大连接数
        max-active: 5
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 5
        #最小空闲
        min-idle: 2
        #连接超时时间
      timeout: 10000
mybatis-plus:
  configuration:
    # 开启驼峰转下划线（默认为true）
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  # 配置枚举 支持通配符 * 或者 ; 分割
  type-enums-package: cn.wlih.core.dbEnum
  global-config:
    db-config:
#      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2(逻辑删除字段上添加 @TableLogic 注解))
      logic-delete-value: -1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)

# Knife4j API文档配置
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: order
  api-docs:
    path: /v3/api-docs
  default-flat-param-object: false
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: Copyright © [王立宏](http://wlih.cn/) 2023-2024
common-swagger:
  # 当enabled为false的时候，则可禁用swagger。
  enabled: true
  # 工程的基础包名。
  basePackage: cn
  # 工程服务的基础包名。
  serviceBasePackage: cn.wlih
  title: 跨境（中越）物流信息监控系统
  description: 跨境（中越）物流信息监控系统详情
  version: 1.0

