server:
  port: 8082
spring:
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://db.wlih.cn:3307/test?characterEncoding=utf-8&serverTimezone=UTC
    username: testAdmin
    password: testAdmin
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    #数据库索引
    database: 0
    host: db.wlih.cn
    port: 6379
    password: Admin@10086
    jedis:
      pool:
        #最大连接数
        max-active: 5
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 5
        #最小空闲
        min-idle: 2
        #连接超时时间
      timeout: 10000
mybatis-plus:
  configuration:
    # 开启驼峰转下划线（默认为true）
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl