logging:
  config: classpath:logback-spring.xml
  level:
    # 这里设置的日志级别优先于logback-spring.xml文件Loggers中的日志级别。
    cn.wlih: trace
server:
  port: 8080
spring:
  servlet:
    multipart:
      # 设置单个文件的最大大小
      max-file-size: 20MB
      # 设置请求的最大大小（包含所有文件）
      max-request-size: 35MB
  #  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://wlih.cn:3307/sensor_module?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: SensorModule
    password: SensorModule_mima202001040435
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池
    hikari:
      #连接池名
      pool-name: cn_wlih_sensor_module
      #最小空闲连接数
      minimum-idle: 10
      # 空闲连接存活最大时间3分50秒（数据库会删除4分钟内没有请求的连接，故而该值最好小于4分钟），默认600000（10分钟）
      idle-timeout: 230000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 20
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟。（数据库会删除4分钟内没有请求的连接，故而该值最好小于4分钟）
      max-lifetime: 235000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    #数据库索引
    database: 0
    host: db.wlih.cn
    port: 6379
    password: Admin@10086
    jedis:
      pool:
        #最大连接数
        max-active: 5
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 5
        #最小空闲
        min-idle: 2
        #连接超时时间
      timeout: 10000

# 自动分页的配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: false
  params: count=countSql

mybatis-plus:
  mapper-locations: classpath:cn/wlih/upms/dao/mapper/*Mapper.xml,cn/wlih/app/dao/mapper/*Mapper.xml,cn/wlih/sensormodule/dao/mapper/*Mapper.xml
  type-aliases-package: cn.wlih.upms.model,cn.wlih.app.model,cn.wlih.sensormodule.model
  configuration:
    # 开启驼峰转下划线（默认为true）
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑已删除值(默认为 1)
      logic-delete-value: -1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 1

# Knife4j API文档配置
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: order
  api-docs:
    path: /v3/api-docs
  default-flat-param-object: false
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: Copyright © [王立宏](http://wlih.cn/) 2023-2024 [滇ICP备2024027005号](https://beian.miit.gov.cn/)
common-swagger:
  # 当enabled为false的时候，则可禁用swagger。
  enabled: true
  # 工程的基础包名。
  basePackage: cn
  # 工程服务的基础包名。
  serviceBasePackage: cn.wlih
  title: 毕业设计 —— 跨境（中越）物流信息监控系统
  description: 跨境（中越）物流信息监控系统 毕设后端API文档
  version: 1.0

# ID生成策略
common-sequence:
  snowflakeWorkNode: 1

# netty-socketio 配置
socketio:
  host: 0.0.0.0
  port: 8081
  # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
  maxFramePayloadLength: 1048576
  # 设置http交互最大内容长度
  maxHttpContentLength: 1048576
  # socket连接数大小（如只监听一个端口boss线程组为1即可）
  bossCount: 1
  workCount: 100
  allowCustomRequests: true
  # 协议升级超时时间（毫秒），默认10秒。HTTP握手升级为ws协议超时时间
  upgradeTimeout: 1000000
  # Ping消息超时时间（毫秒），默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
  pingTimeout: 6000000
  # Ping消息间隔（毫秒），默认25秒。客户端向服务器发送一条心跳消息间隔
  pingInterval: 25000
